import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Fragment } from "react";

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/forum/areas">Areas</Link>
    </Fragment>
  );
};

export default Home;
