version: '3.4'

services:
  identitydb:
    container_name: IdentityDb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=Identity
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - identity_data:/var/lib/postgresql/data/

  chatdb:
    container_name: ChatDb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=Chat
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - chat_data:/var/lib/postgresql/data/

  forumdb:
    container_name: ForumDb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=Forum
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - forum_data:/var/lib/postgresql/data/

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=davidnnon@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=Server=identitydb;Port=5432;Database=Identity;User Id=admin;Password=password;
      - MvcClient=http://host.docker.internal:8010
    depends_on:
      - identitydb
    ports:
      - "8000:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  chat.api:
    container_name: chat.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=Server=chatdb;Port=5432;Database=Chat;User Id=admin;Password=password;
      - EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - chatdb
      - rabbitmq
    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  forum.api:
    container_name: forum.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=Server=forumdb;Port=5432;Database=Forum;User Id=admin;Password=password;
      - HashId:Salt=b831a425-4b75-4986-aea8-e8269cb74bb3
      - HashId:Length=8
      - EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - forumdb
      - rabbitmq
    ports:
      - "8002:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro