version: '3.4'

services:
  chatdb:
    image: postgres

  forumdb:
    image: postgres

  identitydb:
    image: postgres
    
  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4

  chat.api:
    image: ${DOCKER_REGISTRY-}chatapi
    build:
      context: .
      dockerfile: Services/Chat/Chat.API/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Services/Identity/IdentityServer/Dockerfile

  forum.api:
    image: ${DOCKER_REGISTRY-}forumapi
    build:
      context: .
      dockerfile: Services/Forum/Forum.API/Dockerfile

volumes:
  chat_data:
  forum_data:
  identity_data:
  pgadmin_data:
